### ISSUE TITLE
The package doesn't work

### ISSUE THREAD

**Issue by kasiaizak** [lukekarrys/git-directory-deploy#10]
Hi, I installed the package with npm: `npm install git-directory-deploy --save-dev`.
Then I added in the package.json file, in scripts: `"scripts": {"deploy": "git-directory-deploy --directory _dist --branch page"},`.
I run the script with the command: `npm run deploy`
Unfortunately, my _dist_ catalog doesn't want to be published on the _page_ branch

```
$ npm run deploy

> wtf-gulp-starter@1.0.0 predeploy C:\Users\izak\Repo\priv\business-card
> gulp build

[13:58:31] Requiring external module @babel/register
[13:58:35] Using gulpfile ~\Repo\priv\business-card\gulpfile.babel.js
[13:58:35] Starting 'build'...
[13:58:35] Starting 'sass'...

  Replace Autoprefixer browsers option to Browserslist config.
  Use browserslist key in package.json or .browserslistrc file.

  Using browsers option cause some error. Browserslist config
  can be used for Babel, Autoprefixer, postcss-normalize and other tools.

  If you really need to use option, rename it to overrideBrowserslist.

  Learn more at:
  https://github.com/browserslist/browserslist#readme
  https://twitter.com/browserslist


[13:58:35] Finished 'sass' after 219 ms
[13:58:35] Starting 'html'...
[13:58:35] Finished 'html' after 10 ms
[13:58:35] Starting 'js'...
[13:58:37] Version: webpack 4.41.0
Built at: 2019-10-08 13:58:37
  Asset        Size    Chunks               Chunk Names
main.js    26.1 KiB         0  [emitted]    main
Entrypoint main = main.js
[13:58:37] Finished 'js' after 1.52 s
[13:58:37] Starting 'assets'...
[13:58:37] Finished 'assets' after 44 ms
[13:58:37] Finished 'build' after 1.8 s

> wtf-gulp-starter@1.0.0 deploy C:\Users\izak\Repo\priv\business-card
> git-directory-deploy --directory _dist --branch page

internal/child_process.js:366
    throw errnoException(err, 'spawn');
    ^

Error: spawn UNKNOWN
    at ChildProcess.spawn (internal/child_process.js:366:11)
    at spawn (child_process.js:538:9)
    at Object. (C:\Users\izak\Repo\priv\business-card\node_modules\git-directory-deploy\index.js:9:15)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wtf-gulp-starter@1.0.0 deploy: `git-directory-deploy --directory _dist --branch page`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wtf-gulp-starter@1.0.0 deploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\izak\AppData\Roaming\npm-cache\_logs\2019-10-08T11_58_38_166Z-debug.log
```

What am I doing wrong?

**Comment by lukekarrys** [comment]
It looks like you're using it correctly, and I was able to run a similar command using the latest version on my machine. I found some other projects with reports of the same `Error: spawn UNKNOWN` error on Windows. Unfortunately, I'm unable to test on Windows at the moment, so I don't know how to debug this further. Depending on the version of node/npm you have, it might be worth it to try updating the latest versions and try again? Sorry for not being able to help further.

**Comment by kasiaizak** [comment]
Thank You for your response. For now, I returned to the previously used package, which, as it turned out, also gives you the opportunity to configure the branch.

**Comment by GeorgeBark** [comment]
> Thank You for your response. For now, I returned to the previously used package, which, as it turned out, also gives you the opportunity to configure the branch.

I am having the same issue...
@kasiaizak what would be that "previously used package"? Did it solve your problem?

Thanks

**Comment by ghost** [comment]
Same issue here on windows!
```
internal/child_process.js:394
    throw errnoException(err, 'spawn');
    ^

Error: spawn UNKNOWN

[...]node_modules\git-directory-deploy\index.js:9:15)
```
